spring.application.name=appointment-service
server.port=8080

spring.datasource.url=${APPOINTMENT_DATASOURCE_URL:jdbc:mysql://appointment-db:3306/appointment_service?createDatabaseIfNotExist=true}
spring.datasource.username=${APPOINTMENT_DATASOURCE_USERNAME:appointment_user}
spring.datasource.password=${APPOINTMENT_DATASOURCE_PASSWORD:appointment_pwd}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true

# SQL init
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:appointment-data.sql

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.org.springframework.jdbc.datasource.init=DEBUG
services.patient.url=${PATIENT_SERVICE_URL:http://patient-service:8080}
services.doctor.url=${DOCTOR_SERVICE_URL:http://doctor-service:8080}
services.clinic-room.url=${CLINIC_ROOM_SERVICE_URL:http://clinic-room-service:8080}


