server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  application:
    name: clinic-room-service
  config:
    activate:
      on-profile: default
  data:
    mongodb:
      uri: mongodb://localhost:27017/clinic_room_service
      auto-index-creation: true

---
spring:
  application:
    name: clinic-room-service
  config:
    activate:
      on-profile: docker
  data:
    mongodb:
      uri: mongodb://clinic_room_root:clinic_room_pwd@clinic-room-db:27017/clinic_room_service?authSource=admin
      auto-index-creation: true

---
spring:
  application:
    name: clinic-room-service
  config:
    activate:
      on-profile: testing
  data:
    mongodb:
      database: clinic_room_service_test
      auto-index-creation: true
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.14
