server:
  port: 8080
  error:
    include-message: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

---
spring:
  application:
    name: clinic-room-service
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:mem:clinic-room-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:clinic-room-data-h2.sql

---
spring:
  application:
    name: clinic-room-service
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://clinic-room-db:5432/clinic_room_service
    username: clinic_room_user
    password: clinic_room_pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:clinic-room-data-postgres.sql

---
spring:
  application:
    name: clinic-room-service
  config:
    activate:
      on-profile: testing
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:clinic-room-db;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      data-locations: classpath:clinic-room-data-h2.sql
