spring.application.name=apigateway-service
server.port=8080
services.patient.url=${PATIENT_SERVICE_URL:http://patient-service:8080}
services.doctor.url=${DOCTOR_SERVICE_URL:http://doctor-service:8080}
services.clinic-room.url=${CLINIC_ROOM_SERVICE_URL:http://clinic-room-service:8080}
services.appointment.url=${APPOINTMENT_SERVICE_URL:http://appointment-service:8080}
